### ISSUE TITLE
Bad Font Rendering

### ISSUE THREAD

**Issue by AlexDev404** [cairoshell/cairoshell#689]
**Describe the bug**
The font rendering of Cairo is inconsistent and badly rendered. There is no font-smoothing.

**Steps to reproduce**
1. Launch Cairo Desktop
2. Observe how the lettering and thickness of the letters is inconsistent, along with its jagged edges.

**Expected behavior**
Clean, anti-aliased, smooth looking fonts that are evenly spaced.

**System information:**
 - Windows version: 11
 - Cairo version: 0.4.198.3828 - Pre-release
 - 32-bit or 64-bit: 64-bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: Yes

**Additional context**
My personal opinion is that this looks very bad. It makes the text on Cairo look very hard-to-read (specifically talking about the [action menu](#a_menu) for Cairo)

The [font hinting](#f_hint) is also messed up, making the lettering look very skewed and inconsistent. 
It also seems as though [anti-aliasing](#a_alias) is off. Is there a way to enable this? The edges of the lettering is very jagged.

**Screenshots**

Comparison of how fonts look in Cairo.
![image](https://user-images.githubusercontent.com/34188635/171312203-1d7656a8-70bd-4531-94be-cf73daed4925.png)

How fonts **SHOULD** (technically, that is) look in Cairo.
![image](https://user-images.githubusercontent.com/34188635/171312249-2ec1c513-7815-4ad2-9fe6-cc95d32191cf.png)

### Font Hinting <a id="f_hint"></a>
![image](https://user-images.githubusercontent.com/34188635/171312439-a8c1061a-2746-48ab-b1c9-728ea79d1eef.png)

### Anti-Aliasing <a id="a_alias"></a>

![image](https://user-images.githubusercontent.com/34188635/171313084-b75570ab-824b-4b97-ab89-a5900a12e1dd.png)

### Action Menu <a id="a_menu"></a>
![image](https://user-images.githubusercontent.com/34188635/171313477-c681d9ea-12cf-42bd-88f2-f111259834a4.png)

**Comment by WesleyBryie** [comment]
This either was fixed or is a problem on your machine... works fine on mine!
![image](https://user-images.githubusercontent.com/93141203/173210738-b3f329bb-5f78-47f9-8d1c-ca93f9bf44cb.png)

**Comment by dremin** [comment]
Have you used ClearType Tuner to adjust font smoothing? I agree this does not look right, but we are not modifying how text is rendered by DirectWrite.

My suggestion is to open ClearType Tuner (you can find it in the Settings app by searching ClearType) and either try the defaults or try some adjustments--I was able to replicate your screenshots by using certain settings there, and was also able to improve font rendering afterwards by running it again and reverting my changes.

Please note that when making changes in ClearType Tuner, the Cairo menu bar won't show them immediately. After finishing the tuner, you can see the results by opening menus in Cairo, or by restarting Cairo.

**Comment by AlexDev404** [comment]
> Have you used ClearType Tuner to adjust font smoothing? I agree this does not look right, but we are not modifying how text is rendered by DirectWrite.
> 
> My suggestion is to open ClearType Tuner (you can find it in the Settings app by searching ClearType) and either try the defaults or try some adjustments--I was able to replicate your screenshots by using certain settings there, and was also able to improve font rendering afterwards by running it again and reverting my changes.
> 
> Please note that when making changes in ClearType Tuner, the Cairo menu bar won't show them immediately. After finishing the tuner, you can see the results by opening menus in Cairo, or by restarting Cairo.

I tried doing that already multiple times, and each time the results are no different. From the time I started using Cairo a couple years ago the font rendering appeared distorted up till now. 

I started using Cairo on my desktop running Windows 10. I have now installed it on my laptop running Windows 11 to now find that the issue still persists.

**Comment by Crystal-RainSlide** [comment]
Also Cairo uses Japanese font under Chinese language setting, which looks weird, or, like older & not configured Linux.

**Comment by AlexDev404** [comment]
> This either was fixed or is a problem on your machine... works fine on mine! ![image](https://user-images.githubusercontent.com/93141203/173210738-b3f329bb-5f78-47f9-8d1c-ca93f9bf44cb.png)

Literally on different machine now after so many years and it still looks the same way.

**Comment by polymo1** [comment]
Do you all have font smoothing on or off?

**Comment by AlexDev404** [comment]
> Do you all have font smoothing on or off?

It's on. I always use ClearType. It's only this app that has the font displaying like this.

**Comment by dremin** [comment]
Can you please check the registry settings mentioned in [this article](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/advanced/cleartype-registry-settings?view=netframeworkdesktop-4.8) and post the values here? I'd like to see if this is just how the system is configured or something else.

**Comment by AlexDev404** [comment]
# Registry Settings for DISPLAY1
`Computer\HKEY_CURRENT_USER\Software\Microsoft\Avalon.Graphics\DISPLAY1`

![Image](https://github.com/user-attachments/assets/123975c1-bf9b-4064-9096-f5dbd13fb059)

| **Name**                         | **Type**     | **Data**                         |
|-----------------------------------|--------------|----------------------------------|
| **Default**                       | REG_SZ      | (value not set)                  |
| **ClearTypeLevel**                | REG_DWORD   | 0x00000064 (100)                 |
| **EnhancedContrastLevel**         | REG_DWORD   | 0x0000012c (300)                            |
| **GammaLevel**                    | REG_DWORD   | 0x00000898 (2200)                |
| **GrayscaleEnhancedContrastLevel**| REG_DWORD   | 0x000000c8 (200)                 |
| **Pixel Structure**               | REG_DWORD   | 0x00000001 (1)                                 |
| **TextContrastLevel**             | REG_DWORD   | 0x00000001 (1)                                 |

**Comment by dremin** [comment]
> # Registry Settings for DISPLAY1
> 
> `Computer\HKEY_CURRENT_USER\Software\Microsoft\Avalon.Graphics\DISPLAY1`
> 
> ![Image](https://github.com/user-attachments/assets/123975c1-bf9b-4064-9096-f5dbd13fb059)
> **Name** 	**Type** 	**Data**
> **(Default)** 	REG_SZ 	(value not set)
> **ClearTypeLevel** 	REG_DWORD 	0x00000064 (100)
> **EnhancedContrastLevel** 	REG_DWORD 	0x0000012c (300)
> **GammaLevel** 	REG_DWORD 	0x00000898 (2200)
> **GrayscaleEnhancedContrastLevel** 	REG_DWORD 	0x000000c8 (200)
> **Pixel Structure** 	REG_DWORD 	0x00000001 (1)
> **TextContrastLevel** 	REG_DWORD 	0x00000001 (1)

Thanks, this is helpful! I have narrowed this down to the `EnhancedContrastLevel` causing Cairo text to look like garbage. The closer this setting moves to 0, the better Cairo text looks. If you remove this setting (or bring it down to 0), then log out and log back in, how do things look for you?

**Comment by Crystal-RainSlide** [comment]
> > Also Cairo uses Japanese font under Chinese language setting, which looks weird, or, like some older & not configured Linux.
> 
> I'm surprised after so many years they still haven't fixed such a simple rendering issue

Seems it's a rendering issue + font choosing issue, since ClearType don't choose fonts.

I think add some font customization can help on the font part. Which also helps those who need to use special fonts.
